version: "3.9"
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "8001:8080"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: mongodb://root:example@mongo:27017/?
    depends_on:
      - mongo
    command: [ "/app/main" ]
  frontend:
    build:
      dockerfile: "Dockerfile.frontend"
      context: "."
      args:
        - API_URL=http://localhost:8001
    depends_on:
      - backend
    restart: always
    ports:
      - "8002:8080"
