version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bhagad_house_booking
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://root:secret@postgres:5432/bhagad_house_booking?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh","postgres:5432","--","/app/start.sh"]
    command: ["/app/main"]
