#Build stage
FROM golang:1.19-alpine3.16 AS buildstage

WORKDIR /app

COPY backend ./backend

COPY common ./common

RUN cd backend && go mod tidy

RUN cd common && go mod tidy

RUN cd backend && go build cmd/server/main.go

# Run stage
FROM alpine:3.16

WORKDIR /app

COPY --from=buildstage /app/backend/main .

EXPOSE 8080
CMD ["/app/main"]
