apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::846889921282:user/bhagad_house_user
      username: bhagad_house_user
      groups:
        - system:masters
