// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type RateTimeUnits string

const (
	RateTimeUnitsDay   RateTimeUnits = "Day"
	RateTimeUnitsHour  RateTimeUnits = "Hour"
	RateTimeUnitsWeek  RateTimeUnits = "Week"
	RateTimeUnitsMonth RateTimeUnits = "Month"
)

func (e *RateTimeUnits) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RateTimeUnits(s)
	case string:
		*e = RateTimeUnits(s)
	default:
		return fmt.Errorf("unsupported scan type for RateTimeUnits: %T", src)
	}
	return nil
}

type NullRateTimeUnits struct {
	RateTimeUnits RateTimeUnits
	Valid         bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRateTimeUnits) Scan(value interface{}) error {
	if value == nil {
		ns.RateTimeUnits, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RateTimeUnits.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRateTimeUnits) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.RateTimeUnits, nil
}

type Booking struct {
	ID           int64           `json:"id"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	StartDate    sql.NullTime    `json:"start_date"`
	EndDate      sql.NullTime    `json:"end_date"`
	CustomerID   sql.NullInt64   `json:"customer_id"`
	Rate         sql.NullFloat64 `json:"rate"`
	RateTimeUnit RateTimeUnits   `json:"rate_time_unit"`
}

type Customer struct {
	ID        int64        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	Name      string       `json:"name"`
	Address   string       `json:"address"`
	Phone     string       `json:"phone"`
	Email     string       `json:"email"`
}
